-- =============================================================
-- APIARIO LA RUDA - PEDIDOS MIXTOS V3
-- Ejecutar UNA VEZ en Supabase > SQL Editor > Run.
--
-- Agrega:
--   * catálogo identificable de productos en order_items
--   * preparación independiente de NÚCLEOS
--   * preparación independiente de REINAS
--   * historial de ambas preparaciones
--   * seguimiento público compatible con pedidos mixtos
--
-- NO elimina pedidos existentes.
-- =============================================================

begin;

-- 1) Nuevos campos de preparación en pedidos.
alter table public.orders
  add column if not exists nucleo_stage text not null default 'pendiente'
    check (nucleo_stage in ('pendiente', 'material_preparado', 'reina_fecundada'));

alter table public.orders
  add column if not exists reina_stage text not null default 'pendiente'
    check (reina_stage in ('pendiente', 'reina_fecundada', 'reina_encerrada'));

-- 2) Identificación de artículos por catálogo.
alter table public.order_items add column if not exists product_code text;
alter table public.order_items add column if not exists product_type text;

-- Si el constraint ya existe, no lo duplicamos.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'order_items_product_type_check'
      and conrelid = 'public.order_items'::regclass
  ) then
    alter table public.order_items
      add constraint order_items_product_type_check
      check (product_type is null or product_type in ('nucleo', 'reina', 'general'));
  end if;
end $$;

-- 3) Clasificar pedidos/artículos existentes para no perder compatibilidad.
update public.order_items
set product_type = case
  when lower(description) like '%núcleo%' or lower(description) like '%nucleo%' then 'nucleo'
  when lower(description) like '%reina%' and lower(description) not like '%jaula%' then 'reina'
  else 'general'
end
where product_type is null;

update public.order_items
set product_code = case
  when product_type = 'nucleo' and lower(description) like '%baby%' then 'nucleo_baby_vivo'
  when product_type = 'nucleo' then 'nucleo_estandar'
  when product_type = 'reina' then 'reina_fecundada'
  when lower(description) like '%alimentador%' then 'alimentador_externo'
  when lower(description) like '%jaula%' then 'jaula_belton'
  when lower(description) like '%miel%' and lower(description) like '%500%' then 'miel_500g'
  when lower(description) like '%miel%' then 'miel_1kg'
  else product_code
end
where product_code is null;

-- 4) Migrar estados preparatorios viejos al nuevo esquema.
update public.orders o
set nucleo_stage = case
  when o.status = 'reina_fecundada' then 'reina_fecundada'
  when o.status = 'material_preparado' then 'material_preparado'
  else o.nucleo_stage
end
where o.status in ('material_preparado', 'reina_fecundada')
  and exists (
    select 1 from public.order_items i
    where i.order_id = o.id and i.product_type = 'nucleo'
  );

update public.orders o
set reina_stage = case
  when o.status = 'reina_fecundada' then 'reina_fecundada'
  when o.status = 'material_preparado' then 'reina_encerrada'
  else o.reina_stage
end
where o.status in ('material_preparado', 'reina_fecundada')
  and exists (
    select 1 from public.order_items i
    where i.order_id = o.id and i.product_type = 'reina'
  );

-- Los estados preparatorios dejan de vivir en orders.status.
update public.orders
set status = 'pedido_ingresado'
where status in ('material_preparado', 'reina_fecundada');

-- 5) Historial específico de las dos preparaciones.
create table if not exists public.order_preparation_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  preparation_type text not null check (preparation_type in ('nucleo', 'reina')),
  stage text not null,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create index if not exists idx_order_preparation_history_order
  on public.order_preparation_history (order_id, preparation_type, created_at);

alter table public.order_preparation_history enable row level security;
revoke all on table public.order_preparation_history from anon;
grant select, insert, update, delete on table public.order_preparation_history to authenticated;
grant usage, select on sequence public.order_preparation_history_id_seq to authenticated;

drop policy if exists admin_order_preparation_history_all on public.order_preparation_history;
create policy admin_order_preparation_history_all
on public.order_preparation_history
for all to authenticated
using (public.la_ruda_is_admin())
with check (public.la_ruda_is_admin());

-- Recuperar del historial viejo las etapas de preparación cuando sea posible.
insert into public.order_preparation_history (order_id, preparation_type, stage, created_at, created_by)
select h.order_id, 'nucleo', h.status, h.created_at, h.created_by
from public.order_status_history h
where h.status in ('material_preparado', 'reina_fecundada')
  and exists (
    select 1 from public.order_items i
    where i.order_id = h.order_id and i.product_type = 'nucleo'
  )
  and not exists (
    select 1 from public.order_preparation_history ph
    where ph.order_id = h.order_id
      and ph.preparation_type = 'nucleo'
      and ph.stage = h.status
      and ph.created_at = h.created_at
  );

insert into public.order_preparation_history (order_id, preparation_type, stage, created_at, created_by)
select h.order_id,
       'reina',
       case when h.status = 'material_preparado' then 'reina_encerrada' else 'reina_fecundada' end,
       h.created_at,
       h.created_by
from public.order_status_history h
where h.status in ('material_preparado', 'reina_fecundada')
  and exists (
    select 1 from public.order_items i
    where i.order_id = h.order_id and i.product_type = 'reina'
  )
  and not exists (
    select 1 from public.order_preparation_history ph
    where ph.order_id = h.order_id
      and ph.preparation_type = 'reina'
      and ph.stage = case when h.status = 'material_preparado' then 'reina_encerrada' else 'reina_fecundada' end
      and ph.created_at = h.created_at
  );

-- 6) Trigger que registra cada avance de cada preparación.
create or replace function public.log_order_preparation_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.nucleo_stage is distinct from old.nucleo_stage
     and new.nucleo_stage <> 'pendiente' then
    insert into public.order_preparation_history(order_id, preparation_type, stage, created_by)
    values (new.id, 'nucleo', new.nucleo_stage, auth.uid());
  end if;

  if new.reina_stage is distinct from old.reina_stage
     and new.reina_stage <> 'pendiente' then
    insert into public.order_preparation_history(order_id, preparation_type, stage, created_by)
    values (new.id, 'reina', new.reina_stage, auth.uid());
  end if;

  return new;
end;
$$;

drop trigger if exists trg_order_preparation_history on public.orders;
create trigger trg_order_preparation_history
after update of nucleo_stage, reina_stage on public.orders
for each row execute function public.log_order_preparation_change();

-- 7) RPC pública: no devuelve nombre, teléfono, email ni notas internas.
create or replace function public.get_public_order(p_tracking_code text)
returns jsonb
language sql
security definer
stable
set search_path = public
as $$
  select jsonb_build_object(
    'tracking_code', o.tracking_code,
    'status', o.status,
    'nucleo_stage', o.nucleo_stage,
    'reina_stage', o.reina_stage,
    'estimated_date', o.estimated_date,
    'delivery_method', o.delivery_method,
    'public_note', o.public_note,
    'created_at', o.created_at,
    'updated_at', o.updated_at,
    'items', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'product_code', i.product_code,
          'product_type', i.product_type,
          'description', i.description,
          'quantity', i.quantity,
          'unit', i.unit
        ) order by i.sort_order, i.id
      )
      from public.order_items i
      where i.order_id = o.id
    ), '[]'::jsonb),
    'history', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'status', h.status,
          'created_at', h.created_at
        ) order by h.created_at, h.id
      )
      from public.order_status_history h
      where h.order_id = o.id
    ), '[]'::jsonb),
    'prep_history', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'preparation_type', h.preparation_type,
          'stage', h.stage,
          'created_at', h.created_at
        ) order by h.created_at, h.id
      )
      from public.order_preparation_history h
      where h.order_id = o.id
    ), '[]'::jsonb)
  )
  from public.orders o
  where upper(trim(o.tracking_code)) = upper(trim(p_tracking_code))
  limit 1;
$$;

revoke all on function public.get_public_order(text) from public;
grant execute on function public.get_public_order(text) to anon, authenticated;

NOTIFY pgrst, 'reload schema';
commit;

-- Verificación final.
select
  'OK - V3 pedidos mixtos instalada' as resultado,
  exists(select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='nucleo_stage') as nucleo_stage,
  exists(select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='reina_stage') as reina_stage,
  exists(select 1 from information_schema.tables where table_schema='public' and table_name='order_preparation_history') as historial_preparacion;
