-- =============================================================
-- APIARIO LA RUDA - PEDIDOS Y SEGUIMIENTO
-- Ejecutar TODO este archivo en Supabase > SQL Editor.
-- =============================================================

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  tracking_code text not null unique default (
    'LR-' || to_char(now(), 'YY') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
  ),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  status text not null default 'pedido_ingresado' check (status in (
    'pedido_ingresado',
    'material_preparado',
    'reina_fecundada',
    'pendiente_pago',
    'pago_confirmado',
    'envio',
    'finalizado'
  )),
  estimated_date date,
  delivery_method text not null default 'A coordinar',
  total numeric(12,2) not null default 0 check (total >= 0),
  public_note text,
  internal_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  updated_by uuid default auth.uid()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  description text not null,
  quantity numeric(10,2) not null default 1 check (quantity > 0),
  unit text not null default 'u.',
  unit_price numeric(12,2) check (unit_price is null or unit_price >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null check (status in (
    'pedido_ingresado',
    'material_preparado',
    'reina_fecundada',
    'pendiente_pago',
    'pago_confirmado',
    'envio',
    'finalizado'
  )),
  note text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

create index if not exists idx_orders_tracking_code on public.orders (tracking_code);
create index if not exists idx_orders_status on public.orders (status);
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_order_items_order_id on public.order_items (order_id);
create index if not exists idx_order_status_history_order_id on public.order_status_history (order_id, created_at);

create or replace function public.set_order_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  return new;
end;
$$;

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.set_order_updated_at();

create or replace function public.log_order_status_change()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.order_status_history (order_id, status, created_by)
    values (new.id, new.status, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_order_status_history on public.orders;
create trigger trg_order_status_history
after insert or update of status on public.orders
for each row execute function public.log_order_status_change();

-- =============================================================
-- SEGURIDAD
-- Solo el usuario administrador autenticado puede leer/escribir
-- tablas internas. El cliente público NO tiene SELECT directo.
-- =============================================================

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

revoke all on table public.orders from anon;
revoke all on table public.order_items from anon;
revoke all on table public.order_status_history from anon;

grant select, insert, update, delete on table public.orders to authenticated;
grant select, insert, update, delete on table public.order_items to authenticated;
grant select, insert, update, delete on table public.order_status_history to authenticated;
grant usage, select on sequence public.order_items_id_seq to authenticated;
grant usage, select on sequence public.order_status_history_id_seq to authenticated;

drop policy if exists admin_orders_all on public.orders;
create policy admin_orders_all
on public.orders
for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@apiariolaruda.local')
with check ((auth.jwt() ->> 'email') = 'admin@apiariolaruda.local');

drop policy if exists admin_order_items_all on public.order_items;
create policy admin_order_items_all
on public.order_items
for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@apiariolaruda.local')
with check ((auth.jwt() ->> 'email') = 'admin@apiariolaruda.local');

drop policy if exists admin_order_history_all on public.order_status_history;
create policy admin_order_history_all
on public.order_status_history
for all
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@apiariolaruda.local')
with check ((auth.jwt() ->> 'email') = 'admin@apiariolaruda.local');

-- =============================================================
-- FUNCIÓN PÚBLICA DE SEGUIMIENTO
-- Devuelve solamente los datos que el comprador puede ver.
-- No expone teléfono, email, notas internas ni datos de otros pedidos.
-- =============================================================

create or replace function public.get_public_order(p_tracking_code text)
returns jsonb
language sql
security definer
stable
set search_path = public
as $$
  select jsonb_build_object(
    'tracking_code', o.tracking_code,
    'status', o.status,
    'estimated_date', o.estimated_date,
    'delivery_method', o.delivery_method,
    'public_note', o.public_note,
    'created_at', o.created_at,
    'updated_at', o.updated_at,
    'items', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'description', i.description,
          'quantity', i.quantity,
          'unit', i.unit
        )
        order by i.sort_order, i.id
      )
      from public.order_items i
      where i.order_id = o.id
    ), '[]'::jsonb),
    'history', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'status', h.status,
          'created_at', h.created_at
        )
        order by h.created_at, h.id
      )
      from public.order_status_history h
      where h.order_id = o.id
    ), '[]'::jsonb)
  )
  from public.orders o
  where upper(trim(o.tracking_code)) = upper(trim(p_tracking_code))
  limit 1;
$$;

revoke all on function public.get_public_order(text) from public;
grant execute on function public.get_public_order(text) to anon, authenticated;



-- =============================================================
-- KEEPALIVE PARA PLAN FREE
--
-- Esta función está pensada para ser llamada por un servicio externo
-- (por ejemplo cron-job.org) varias veces al día. Hace una lectura mínima
-- de la tabla de pedidos y NO crea, modifica ni elimina información.
-- =============================================================

create or replace function public.la_ruda_keepalive()
returns jsonb
language sql
security definer
stable
set search_path = public
as $$
  select jsonb_build_object(
    'ok', (select count(*) from public.orders) >= 0,
    'checked_at', now()
  );
$$;

revoke all on function public.la_ruda_keepalive() from public;
grant execute on function public.la_ruda_keepalive() to anon, authenticated;

-- =============================================================
-- FIN
-- =============================================================


-- =============================================================
-- ADMINISTRADOR POR UUID + RPC DE VALIDACIÓN
-- =============================================================

create table if not exists public.la_ruda_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.la_ruda_admins enable row level security;
revoke all on table public.la_ruda_admins from anon, authenticated;

do $$
declare
  v_user uuid;
  v_auth_count integer;
  v_admin_count integer;
begin
  select count(*) into v_admin_count from public.la_ruda_admins;
  if v_admin_count = 0 then
    select id into v_user
    from auth.users
    where lower(email) = 'admin@apiariolaruda.local'
    order by created_at
    limit 1;

    if v_user is null then
      select count(*) into v_auth_count from auth.users;
      if v_auth_count = 1 then
        select id into v_user from auth.users order by created_at limit 1;
      end if;
    end if;

    if v_user is null then
      raise exception 'No pude determinar automáticamente el administrador. Hay varios usuarios en Authentication > Users.';
    end if;

    insert into public.la_ruda_admins(user_id) values (v_user)
    on conflict (user_id) do nothing;
  end if;
end $$;

drop function if exists public.la_ruda_is_admin();
create function public.la_ruda_is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.la_ruda_admins a where a.user_id = auth.uid()
  );
$$;

revoke all on function public.la_ruda_is_admin() from public;
grant execute on function public.la_ruda_is_admin() to authenticated;

drop policy if exists admin_orders_all on public.orders;
create policy admin_orders_all on public.orders
for all to authenticated
using (public.la_ruda_is_admin())
with check (public.la_ruda_is_admin());

drop policy if exists admin_order_items_all on public.order_items;
create policy admin_order_items_all on public.order_items
for all to authenticated
using (public.la_ruda_is_admin())
with check (public.la_ruda_is_admin());

drop policy if exists admin_order_history_all on public.order_status_history;
create policy admin_order_history_all on public.order_status_history
for all to authenticated
using (public.la_ruda_is_admin())
with check (public.la_ruda_is_admin());

NOTIFY pgrst, 'reload schema';
